### ISSUE TITLE
Invalid argument 1 passed to Omniphx\Forrest\Providers\Laravel\LaravelCache

### ISSUE THREAD

**Issue by pawelryznar** [omniphx/forrest#161]
Code fails because of wrong types passed to the LaravelCache constructor.

In Omniphx\Forrest\Providers\Laravel\ForrestServiceProvider::getStorage
```
            case 'cache':
                $storage = new LaravelCache(app('config'), app('cache'));
                break;
```
Parameters in the constructor have a wrong order. It should be  
`$storage = new LaravelCache(app('cache'), app('config'));`

**Comment by omniphx** [comment]
Can you install `dev-master` now and confirm this is working?

**Comment by murwa** [comment]
will try and update, thanks @omniphx

**Comment by omniphx** [comment]
Fixed in version 2.4.2

**Comment by provun** [comment]
I am still getting this issue with both 2.4.2 and 2.4.3. Any ideas on how to solve?

**Comment by omniphx** [comment]
@provun, which version of Laravel are you using?

**Comment by provun** [comment]
5.3.31
